# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0003_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='activationkey',
            field=models.CharField(default='', max_length=255),
        ),
    ]
