# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0005_auto_20161225_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='activationkey',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='resetkey',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
