# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0006_auto_20161225_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='resetkeyexpirytime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
