# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0007_extendeduser_resetkeyexpirytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='resetkeyexpirytime',
            field=models.IntegerField(),
        ),
    ]
