# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0008_auto_20161225_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='resetkey',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='resetkeyexpirytime',
            field=models.IntegerField(default=0),
        ),
    ]
