# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0009_auto_20161226_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='approval',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='review_ready',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='weights',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
