# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc510project', '0010_auto_20161229_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
